from ContestIndices import *

states_array = []
congressional_district_ME_array = []
congressional_district_NE_array = []

# Add states and DC to our array in alphabetical order:
states_array.insert(array_index_AL, "Alabama")
states_array.insert(array_index_AK, "Alaska")
states_array.insert(array_index_AZ, "Arizona")
states_array.insert(array_index_AR, "Arkansas")
states_array.insert(array_index_CA, "California")
states_array.insert(array_index_CO, "Colorado")
states_array.insert(array_index_CT, "Connecticut")
states_array.insert(array_index_DE, "Delaware")
states_array.insert(array_index_DC, "District of Columbia")
states_array.insert(array_index_FL, "Florida")
states_array.insert(array_index_GA, "Georgia")
states_array.insert(array_index_HI, "Hawaii")
states_array.insert(array_index_ID, "Idaho")
states_array.insert(array_index_IL, "Illinois")
states_array.insert(array_index_IN, "Indiana")
states_array.insert(array_index_IA, "Iowa")
states_array.insert(array_index_KS, "Kansas")
states_array.insert(array_index_KY, "Kentucky")
states_array.insert(array_index_LA, "Louisiana")
states_array.insert(array_index_ME, "Maine")
states_array.insert(array_index_MD, "Maryland")
states_array.insert(array_index_MA, "Massachusetts")
states_array.insert(array_index_MI, "Michigan")
states_array.insert(array_index_MN, "Minnesota")
states_array.insert(array_index_MS, "Mississippi")
states_array.insert(array_index_MO, "Missouri")
states_array.insert(array_index_MT, "Montana")
states_array.insert(array_index_NE, "Nebraska")
states_array.insert(array_index_NV, "Nevada")
states_array.insert(array_index_NH, "New Hampshire")
states_array.insert(array_index_NJ, "New Jersey")
states_array.insert(array_index_NM, "New Mexico")
states_array.insert(array_index_NY, "New York")
states_array.insert(array_index_NC, "North Carolina")
states_array.insert(array_index_ND, "North Dakota")
states_array.insert(array_index_OH, "Ohio")
states_array.insert(array_index_OK, "Oklahoma")
states_array.insert(array_index_OR, "Oregon")
states_array.insert(array_index_PA, "Pennsylvania")
states_array.insert(array_index_RI, "Rhode Island")
states_array.insert(array_index_SC, "South Carolina")
states_array.insert(array_index_SD, "South Dakota")
states_array.insert(array_index_TN, "Tennessee")
states_array.insert(array_index_TX, "Texas")
states_array.insert(array_index_UT, "Utah")
states_array.insert(array_index_VT, "Vermont")
states_array.insert(array_index_VA, "Virginia")
states_array.insert(array_index_WA, "Washington")
states_array.insert(array_index_WV, "West Virginia")
states_array.insert(array_index_WI, "Wisconsin")
states_array.insert(array_index_WY, "Wyoming")

congressional_district_ME_array.insert(array_index_ME_CD1, "Maine Congressional District 1")
congressional_district_ME_array.insert(array_index_ME_CD2, "Maine Congressional District 2")

congressional_district_NE_array.insert(array_index_NE_CD1, "Nebraska Congressional District 1")
congressional_district_NE_array.insert(array_index_NE_CD2, "Nebraska Congressional District 2")
congressional_district_NE_array.insert(array_index_NE_CD3, "Nebraska Congressional District 3")