from ContestIndices import *

recount_margin_votes_states_array = []

# Recount Margins (from Ballotopedia)
# States assigned 0 do not have vote recount margins.

recount_margin_votes_AL = 0
recount_margin_votes_AK = 0
recount_margin_votes_AZ = 200
recount_margin_votes_AR = 0
recount_margin_votes_CA = 0
recount_margin_votes_CO = 0
recount_margin_votes_CT = 0
recount_margin_votes_DC = 0
recount_margin_votes_DE = 0
recount_margin_votes_FL = 0
recount_margin_votes_GA = 0
recount_margin_votes_HI = 0
recount_margin_votes_ID = 0
recount_margin_votes_IL = 0
recount_margin_votes_IN = 0
recount_margin_votes_IA = 0
recount_margin_votes_KS = 0
recount_margin_votes_KY = 0
recount_margin_votes_LA = 0
recount_margin_votes_ME = 0
recount_margin_votes_MD = 0
recount_margin_votes_MA = 0
recount_margin_votes_MI = 2_000
recount_margin_votes_MN = 0
recount_margin_votes_MS = 0
recount_margin_votes_MO = 0
recount_margin_votes_MT = 0
recount_margin_votes_NE = 0
recount_margin_votes_NV = 0
recount_margin_votes_NH = 0
recount_margin_votes_NJ = 0
recount_margin_votes_NM = 0
recount_margin_votes_NY = 0
recount_margin_votes_NC = 10_000
recount_margin_votes_ND = 0
recount_margin_votes_OH = 0
recount_margin_votes_OK = 0
recount_margin_votes_OR = 0
recount_margin_votes_PA = 0
recount_margin_votes_RI = 0
recount_margin_votes_SC = 0
recount_margin_votes_SD = 0
recount_margin_votes_TN = 0
recount_margin_votes_TX = 0
recount_margin_votes_UT = 0
recount_margin_votes_VT = 0
recount_margin_votes_VA = 0
recount_margin_votes_WA = 0
recount_margin_votes_WV = 0
recount_margin_votes_WI = 0
recount_margin_votes_WY = 0

# Create an array:
recount_margin_votes_states_array.insert(array_index_AL, recount_margin_votes_AL)
recount_margin_votes_states_array.insert(array_index_AK, recount_margin_votes_AK)
recount_margin_votes_states_array.insert(array_index_AZ, recount_margin_votes_AZ)
recount_margin_votes_states_array.insert(array_index_AR, recount_margin_votes_AR)
recount_margin_votes_states_array.insert(array_index_CA, recount_margin_votes_CA)
recount_margin_votes_states_array.insert(array_index_CO, recount_margin_votes_CO)
recount_margin_votes_states_array.insert(array_index_CT, recount_margin_votes_CT)
recount_margin_votes_states_array.insert(array_index_DE, recount_margin_votes_DE)
recount_margin_votes_states_array.insert(array_index_DC, recount_margin_votes_DC)
recount_margin_votes_states_array.insert(array_index_FL, recount_margin_votes_FL)
recount_margin_votes_states_array.insert(array_index_GA, recount_margin_votes_GA)
recount_margin_votes_states_array.insert(array_index_HI, recount_margin_votes_HI)
recount_margin_votes_states_array.insert(array_index_ID, recount_margin_votes_ID)
recount_margin_votes_states_array.insert(array_index_IL, recount_margin_votes_IL)
recount_margin_votes_states_array.insert(array_index_IN, recount_margin_votes_IN)
recount_margin_votes_states_array.insert(array_index_IA, recount_margin_votes_IA)
recount_margin_votes_states_array.insert(array_index_KS, recount_margin_votes_KS)
recount_margin_votes_states_array.insert(array_index_KY, recount_margin_votes_KY)
recount_margin_votes_states_array.insert(array_index_LA, recount_margin_votes_LA)
recount_margin_votes_states_array.insert(array_index_ME, recount_margin_votes_ME)
recount_margin_votes_states_array.insert(array_index_MD, recount_margin_votes_MD)
recount_margin_votes_states_array.insert(array_index_MA, recount_margin_votes_MA)
recount_margin_votes_states_array.insert(array_index_MI, recount_margin_votes_MI)
recount_margin_votes_states_array.insert(array_index_MN, recount_margin_votes_MN)
recount_margin_votes_states_array.insert(array_index_MS, recount_margin_votes_MS)
recount_margin_votes_states_array.insert(array_index_MO, recount_margin_votes_MO)
recount_margin_votes_states_array.insert(array_index_MT, recount_margin_votes_MT)
recount_margin_votes_states_array.insert(array_index_NE, recount_margin_votes_NE)
recount_margin_votes_states_array.insert(array_index_NV, recount_margin_votes_NV)
recount_margin_votes_states_array.insert(array_index_NH, recount_margin_votes_NH)
recount_margin_votes_states_array.insert(array_index_NJ, recount_margin_votes_NJ)
recount_margin_votes_states_array.insert(array_index_NM, recount_margin_votes_NM)
recount_margin_votes_states_array.insert(array_index_NY, recount_margin_votes_NY)
recount_margin_votes_states_array.insert(array_index_NC, recount_margin_votes_NC)
recount_margin_votes_states_array.insert(array_index_ND, recount_margin_votes_ND)
recount_margin_votes_states_array.insert(array_index_OH, recount_margin_votes_OH)
recount_margin_votes_states_array.insert(array_index_OK, recount_margin_votes_OK)
recount_margin_votes_states_array.insert(array_index_OR, recount_margin_votes_OR)
recount_margin_votes_states_array.insert(array_index_PA, recount_margin_votes_PA)
recount_margin_votes_states_array.insert(array_index_RI, recount_margin_votes_RI)
recount_margin_votes_states_array.insert(array_index_SC, recount_margin_votes_SC)
recount_margin_votes_states_array.insert(array_index_SD, recount_margin_votes_SD)
recount_margin_votes_states_array.insert(array_index_TN, recount_margin_votes_TN)
recount_margin_votes_states_array.insert(array_index_TX, recount_margin_votes_TX)
recount_margin_votes_states_array.insert(array_index_UT, recount_margin_votes_UT)
recount_margin_votes_states_array.insert(array_index_VT, recount_margin_votes_VT)
recount_margin_votes_states_array.insert(array_index_VA, recount_margin_votes_VA)
recount_margin_votes_states_array.insert(array_index_WA, recount_margin_votes_WA)
recount_margin_votes_states_array.insert(array_index_WV, recount_margin_votes_WV)
recount_margin_votes_states_array.insert(array_index_WI, recount_margin_votes_WI)
recount_margin_votes_states_array.insert(array_index_WY, recount_margin_votes_WY)
